CREATE TABLE Realm (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL DEFAULT '',
    slug VARCHAR(30) NOT NULL DEFAULT ''
);

CREATE TABLE AuctionHouse (
    auction_id BIGINT NOT NULL PRIMARY KEY,
    owner VARCHAR(50) NOT NULL DEFAULT '',
    realm TINYINT UNSIGNED NOT NULL DEFAULT 0,
    bid INT NOT NULL DEFAULT 0,
    buyout INT NOT NULL DEFAULT 0,
    quantity INT NOT NULL DEFAULT 0,
    time_left TINYINT UNSIGNED NOT NULL DEFAULT 0,
    rand INT NOT NULL DEFAULT 0,
    seed BIGINT NOT NULL DEFAULT 0,
    context INT NOT NULL DEFAULT 0
);

CREATE TABLE Item (
    id INT UNSIGNED PRIMARY KEY,
    name VARCHAR(50) NOT NULL DEFAULT '',
    item_class INT NOT NULL DEFAULT 0,
    item_sub_class INT NOT NULL DEFAULT 0,
    item_level INT NOT NULL DEFAULT 0,
    icon VARCHAR(50) NOT NULL DEFAULT '',
    quality INT NOT NULL DEFAULT 0,
    sell_price int NOT NULL DEFAULT 0
);
